# Generated by Django 6.0 on 2026-06-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="exp_type",
            field=models.CharField(
                choices=[("work", "Work"), ("education", "Education")],
                default="work",
                max_length=20,
            ),
        ),
    ]
