# Generated by Django 6.0 on 2026-06-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0002_experience_exp_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
