# Generated by Django 6.0 on 2026-06-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0004_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="icon_name",
            field=models.CharField(
                blank=True,
                help_text="Ionicon nomi, masalan: logo-telegram, globe-outline, phone-portrait-outline",
                max_length=60,
            ),
        ),
    ]
