# Generated by Django 6.0 on 2026-06-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0005_service_icon_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="icon_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("code-slash-outline", "💻 Kod / Dasturlash"),
                    ("terminal-outline", "🖥️ Terminal / Backend"),
                    ("server-outline", "🗄️ Server / API"),
                    ("layers-outline", "📦 Full-stack"),
                    ("globe-outline", "🌐 Web sayt"),
                    ("browsers-outline", "🪟 Frontend"),
                    ("desktop-outline", "🖥 Desktop"),
                    ("phone-portrait-outline", "📱 Mobil ilova"),
                    ("logo-android", "🤖 Android"),
                    ("logo-apple", "🍎 iOS"),
                    ("paper-plane-outline", "✈️ Telegram bot"),
                    ("chatbubbles-outline", "💬 Chat-bot"),
                    ("logo-discord", "🎮 Discord bot"),
                    ("color-palette-outline", "🎨 UI/UX Dizayn"),
                    ("brush-outline", "🖌️ Grafik dizayn"),
                    ("image-outline", "🖼️ Banner / Rasm"),
                    ("trending-up-outline", "📈 SEO / Marketing"),
                    ("megaphone-outline", "📣 Reklama"),
                    ("bar-chart-outline", "📊 Analitika"),
                    ("construct-outline", "🔧 Texnik yordam"),
                    ("shield-checkmark-outline", "🛡️ Xavfsizlik"),
                    ("cloud-upload-outline", "☁️ Hosting / Deploy"),
                    ("settings-outline", "⚙️ Avtolashtirish"),
                    ("camera-outline", "📷 Foto/Video"),
                    ("musical-notes-outline", "🎵 Musiqa / Audio"),
                    ("school-outline", "🎓 Ta'lim / Kurs"),
                ],
                help_text="Xizmat uchun ikonka tanlang",
                max_length=60,
            ),
        ),
    ]
